server:
  port: 8080

spring:
  application:
    name: eshop-portal
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: postgres